
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nec,","EEW46JOH3ZJ","Colon","Caleb","neque@Nullam.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("egestas","TFC93CVL3XR","Kerr","Ebony","ante.bibendum.ullamcorper@iaculis.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("dis","QGY00CST2FD","Greene","Carter","Nunc.laoreet.lectus@veliteusem.com",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fringilla","IXU53RIX6IQ","Macias","Chase","nec.orci@eu.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("viverra.","VJP36TGB0XY","Sheppard","Lunea","vulputate.eu@sed.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Curabitur","UHB01URD1WU","Cherry","Hyatt","metus.urna@est.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vel,","QCR48DLB3UE","Poole","Fleur","rhoncus@diamDuismi.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fermentum","SAZ27YVT9JU","Joyce","Eden","quis.arcu.vel@Loremipsumdolor.edu",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Sed","PHF33NWR8SX","Warren","Harlan","Nunc.mauris.elit@leo.org",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("quis","JNL90ZNQ7UL","Finley","Ariel","Proin@ligulaAliquam.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Quisque","BOJ24NBO6TD","Emerson","Akeem","ante@porta.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("a,","HIG10WGM1WB","Mcclain","Illana","magna.Ut.tincidunt@enimEtiamgravida.ca",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("odio.","XWO43XXL8KB","Ferguson","Ifeoma","eu.eleifend@auguemalesuada.net",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("molestie","YUU17SBJ7VD","Olson","Quamar","neque@rutrumeuultrices.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ipsum","IVG31KHC6QB","Schroeder","Irene","dolor.sit.amet@sagittislobortismauris.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("arcu.","UDE11KSZ4BG","Jenkins","Troy","felis@acliberonec.net",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("tellus.","DII05GTO2SX","Alvarez","Rinah","lacinia.at.iaculis@Utnecurna.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("neque","RZY50XDE1YD","Koch","Gemma","dictum.eu@tincidunttempusrisus.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("accumsan","LLX79EVE8SG","Whitfield","Amaya","arcu.iaculis.enim@VivamusrhoncusDonec.com",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Ut","VEP67BVY8JK","Hahn","Suki","dolor.Quisque.tincidunt@euduiCum.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("venenatis","JZA85OLQ5DY","Durham","Inga","nec.ante@iaculisodio.net",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("risus.","HSN26QVA5PZ","Weiss","Doris","Proin@diamPellentesque.org",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fames","CGH96LTF0WJ","Mckinney","Kelly","Ut.semper@elementum.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Mauris","XWH81HDR5KW","Mays","Alyssa","sed.sapien.Nunc@egestasSedpharetra.com",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("imperdiet","KJE80RII0NL","Austin","Acton","Curabitur.dictum@Maecenaslibero.edu",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("commodo","OAC13ERB1EK","Lloyd","Lawrence","scelerisque@cursuset.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("est","CQP10TWV7KP","Stevenson","Nelle","Cras@euplacerat.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ligula","LGD63LVB0CD","Webster","Evelyn","consectetuer.adipiscing@ante.co.uk",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nibh.","VMH81UDW8IZ","Fox","Giselle","Cras.lorem@dolorsitamet.net",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("accumsan","OKV96IEQ6ZN","Santiago","Patrick","magna.Praesent.interdum@lacus.com",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ornare.","IPJ06LIP8LP","Williamson","Anastasia","lacinia@neque.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("neque","HGH97TRO1GP","Horton","Ria","mauris.sit.amet@velquam.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Donec","DRM71OZA5EE","Stuart","Sasha","quis.arcu@SedmolestieSed.co.uk",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("feugiat.","OKW07BZE3JQ","Norris","Mercedes","non.lobortis.quis@VivamusnisiMauris.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("metus.","TPK53QNW1VW","Camacho","Vivian","aliquet.Phasellus.fermentum@ipsum.com",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("convallis","BNC74RZJ7QE","Riggs","Mason","Mauris.vel.turpis@urnaUttincidunt.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("feugiat","NOG45OSH3PS","Shepard","Jenette","Pellentesque.habitant@nisisemsemper.ca",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vulputate","IQY89PXN1VM","Bolton","Maxwell","vel.est.tempor@vitaeodio.com",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("elementum","UGD35TMJ0XF","Rojas","Anjolie","arcu@velvulputate.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("mauris","RLJ41WQG3FX","Powers","Nathan","posuere@pellentesque.com",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("sodales","PZC57GDK1FM","Hart","Tasha","eget.nisi@Vivamus.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("aliquet.","ORP39NJV9TU","Glover","Dominic","Duis.ac@justofaucibus.co.uk",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ut","BWC81USD7VT","Potts","Nero","lacus@Aliquam.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Nulla","ZBT25RPL5XK","Banks","Mira","arcu.Morbi@tellusid.net",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("lectus","WGB34XIS4ZG","Wells","Samantha","faucibus.Morbi.vehicula@aliquet.net",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("diam.","YRV19NWA8CJ","Mcfarland","Denise","aliquet@necimperdiet.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("aliquet","MNZ23JMZ6WE","Graves","Branden","Nulla.aliquet@Donecelementum.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("dolor","MKU25IZT7UA","Burks","Tanya","lacus.Nulla.tincidunt@tortorIntegeraliquam.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Vestibulum","JWR88ZOC1KM","Burns","Blaze","sem.mollis.dui@fringilla.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ipsum","QPK28HNP0ZR","Suarez","Ima","In.nec.orci@luctusCurabitur.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("velit.","GMP15ETY1RW","Nicholson","Russell","velit.egestas@Fuscediam.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("quis,","ATR11NDU0CS","Briggs","Chandler","sed@sollicitudina.ca",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("auctor","BKG82JWC2HX","Cox","Demetrius","sagittis.semper@velitPellentesqueultricies.com",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("parturient","HLJ98IMQ8CZ","Glenn","Craig","nunc.ac.mattis@tortorInteger.ca",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("rhoncus.","KSD92JEG3ND","Allison","Ariel","ante.ipsum.primis@risus.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Nulla","UKT41JDS4SF","Good","Jocelyn","Aenean@nec.ca",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nulla.","UYE81ITX9NH","Rivers","Amy","sollicitudin.adipiscing@iaculisenimsit.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("luctus","CVH26TXV7JZ","Dennis","Curran","elit.Etiam.laoreet@blanditcongueIn.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("lectus.","KQO73CAS2AU","Gould","Chester","ornare@actellusSuspendisse.com",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nisi.","ROZ09XCX4MK","Barr","Ivor","massa.rutrum@feugiatmetus.org",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vitae","KVK41QJH6VP","Wilder","Kristen","tempor@Maurisnon.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("sit","BXQ82KLG0VC","Morin","Tad","Praesent@ornare.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("id","FHZ67UWY3ZC","Mccarty","Deanna","egestas.Sed.pharetra@convalliserateget.net",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("eros","JWR13ZKO9UF","Moss","Aubrey","sodales@liberoMorbi.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Integer","DNK00SOQ7IQ","Mercer","Kimberly","luctus.felis@sit.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nunc","NAT32GOC1TL","Sweeney","Julie","venenatis.a@sollicitudin.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Suspendisse","IXN49RXR4JA","Sykes","Maxwell","non@tinciduntorci.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ultricies","PNY25KJO9CA","Santos","Philip","fames@egetmetuseu.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("sit","MKK29HSU3RH","Adkins","Bradley","urna.nec@amet.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("diam.","LJT13EEO3KD","Dixon","Hamish","elit.pede@mollis.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("aliquet","SCJ80CKP4CL","Morgan","Abigail","nascetur.ridiculus@Maecenaslibero.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("et","VLV76VVC3EL","Best","Ethan","sit.amet@commodoipsumSuspendisse.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fames","RUL81TQF2RC","Mcguire","Dylan","augue.malesuada@enim.com",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("arcu","JXJ70HXK4MS","Osborne","Daquan","magnis.dis@egetlaoreetposuere.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ante","FOM51XIR8NO","Glover","John","facilisi@Curabiturvel.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vitae","DIR34ZBZ0KX","Guzman","Blaine","pharetra@sed.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("risus","OGO64XNW5RF","Delaney","Nathaniel","Duis.mi@faucibus.edu",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vel,","SJT00UGL6SO","Mcneil","Melyssa","faucibus.orci@ac.com",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("diam","NEQ99HUZ4TI","Buckley","Shelly","at.fringilla.purus@Maurismolestie.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("orci.","EEC88NQB6KJ","Tyson","Sierra","neque@Maecenas.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("euismod","NDU26IWG7YB","Moreno","Guy","eget.nisi@nibh.net",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("neque","HDQ71YKR5FW","Flores","Anjolie","facilisi.Sed@imperdieteratnonummy.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Nulla","ONY49WJL3PS","Moss","Rana","ut@Phasellusdapibusquam.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("convallis,","QZJ23ESV8QV","Porter","Calista","ultrices.iaculis.odio@estvitaesodales.net",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("egestas.","RXK73ZYQ2XZ","Estrada","Amir","lobortis.ultrices.Vivamus@lobortisquam.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("adipiscing","AFB11AVF0RL","Solis","Trevor","eu.euismod@quamelementum.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ornare","KLT72RPT2SW","Kim","Melinda","erat@fringillaporttitorvulputate.edu",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("et,","VFL63NNS4YK","Flynn","Alexis","enim@porttitor.net",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("tellus","QEB62NKW0CB","Graham","Harper","augue.id@augueeu.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("odio.","HSO98HSY2TW","Salazar","Regan","justo@luctusetultrices.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("auctor,","BHR20IEL4EI","Stafford","Eagan","gravida.molestie.arcu@maurisMorbinon.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("egestas","FCX19TEJ2NA","Forbes","Tatiana","eu.accumsan.sed@Curabitur.co.uk",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nec,","EDB09IXS8ED","Olson","Chandler","luctus.et.ultrices@porttitortellus.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("justo.","BCI65ZGZ5KT","Pena","Colton","Nam.porttitor.scelerisque@eu.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("at,","YZT58ZVE1VK","Meyers","Chloe","non@sodalesat.org",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("diam","EPD41SOD4LL","Riggs","Bethany","Cras@ultricesiaculis.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("a","NCL46QPG3PK","Brock","Abbot","dui.in@mollisneccursus.net",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("quam","HQO11SQI0RI","Skinner","Laura","quam.Pellentesque@nonummyultriciesornare.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("tempus","QTA94QYJ7DS","Camacho","Kelsey","convallis.dolor.Quisque@Vestibulumanteipsum.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("turpis.","ODB38JFK1AW","Dotson","Cassady","mauris@cursusinhendrerit.net",3);


INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("egestas",1,1,1);
INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("massa.",1,1,1);
INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("vitae risus.",1,1,1);
INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("faucibus",1,1,1);
INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("ante",1,1,1);
INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("posuere vulputate, lacus.",1,1,1);
INSERT INTO 'autorisations' ('label','peutModifier','peutLire','peutAccorderDroits') VALUES ("nisl.",1,1,1);


INSERT INTO 'statuts' VALUES('consultant',12, 2016);
INSERT INTO 'statuts' VALUES('Enseignant',192, 2016);
INSERT INTO 'statuts' VALUES('enseignant-chercheur',192, 2016);
INSERT INTO 'statuts' VALUES('doctorant',96, 2016);
INSERT INTO 'statuts' VALUES('thésard',20, 2016);


INSERT INTO 'personnelEnseignant' VALUES(50,4);
INSERT INTO 'personnelEnseignant' VALUES(51,1);
INSERT INTO 'personnelEnseignant' VALUES(52,3);
INSERT INTO 'personnelEnseignant' VALUES(53,1);
INSERT INTO 'personnelEnseignant' VALUES(54,2);
INSERT INTO 'personnelEnseignant' VALUES(55,2);
INSERT INTO 'personnelEnseignant' VALUES(56,2);
INSERT INTO 'personnelEnseignant' VALUES(57,2);
INSERT INTO 'personnelEnseignant' VALUES(58,1);
INSERT INTO 'personnelEnseignant' VALUES(59,2);
INSERT INTO 'personnelEnseignant' VALUES(60,1);
INSERT INTO 'personnelEnseignant' VALUES(61,1);
INSERT INTO 'personnelEnseignant' VALUES(62,2);
INSERT INTO 'personnelEnseignant' VALUES(63,1);
INSERT INTO 'personnelEnseignant' VALUES(64,1);
INSERT INTO 'personnelEnseignant' VALUES(65,2);
INSERT INTO 'personnelEnseignant' VALUES(66,1);
INSERT INTO 'personnelEnseignant' VALUES(67,1);
INSERT INTO 'personnelEnseignant' VALUES(68,1);
INSERT INTO 'personnelEnseignant' VALUES(69,1);
INSERT INTO 'personnelEnseignant' VALUES(70,3);
INSERT INTO 'personnelEnseignant' VALUES(71,3);
INSERT INTO 'personnelEnseignant' VALUES(72,2);
INSERT INTO 'personnelEnseignant' VALUES(73,1);
INSERT INTO 'personnelEnseignant' VALUES(74,4);
INSERT INTO 'personnelEnseignant' VALUES(75,2);
INSERT INTO 'personnelEnseignant' VALUES(76,3);
INSERT INTO 'personnelEnseignant' VALUES(77,4);
INSERT INTO 'personnelEnseignant' VALUES(78,1);
INSERT INTO 'personnelEnseignant' VALUES(79,4);
INSERT INTO 'personnelEnseignant' VALUES(80,1);
INSERT INTO 'personnelEnseignant' VALUES(81,1);
INSERT INTO 'personnelEnseignant' VALUES(82,3);
INSERT INTO 'personnelEnseignant' VALUES(83,1);
INSERT INTO 'personnelEnseignant' VALUES(84,4);
INSERT INTO 'personnelEnseignant' VALUES(85,2);
INSERT INTO 'personnelEnseignant' VALUES(86,1);
INSERT INTO 'personnelEnseignant' VALUES(87,1);
INSERT INTO 'personnelEnseignant' VALUES(88,1);
INSERT INTO 'personnelEnseignant' VALUES(89,1);
INSERT INTO 'personnelEnseignant' VALUES(90,4);
INSERT INTO 'personnelEnseignant' VALUES(91,1);
INSERT INTO 'personnelEnseignant' VALUES(92,1);
INSERT INTO 'personnelEnseignant' VALUES(93,4);
INSERT INTO 'personnelEnseignant' VALUES(94,4);
INSERT INTO 'personnelEnseignant' VALUES(95,1);
INSERT INTO 'personnelEnseignant' VALUES(96,1);
INSERT INTO 'personnelEnseignant' VALUES(97,2);
INSERT INTO 'personnelEnseignant' VALUES(98,1);
INSERT INTO 'personnelEnseignant' VALUES(99,1);


INSERT INTO 'personnelAdministratif' VALUES(1);
INSERT INTO 'personnelAdministratif' VALUES(2);
INSERT INTO 'personnelAdministratif' VALUES(3);
INSERT INTO 'personnelAdministratif' VALUES(4);
INSERT INTO 'personnelAdministratif' VALUES(5);
INSERT INTO 'personnelAdministratif' VALUES(6);
INSERT INTO 'personnelAdministratif' VALUES(7);
INSERT INTO 'personnelAdministratif' VALUES(8);
INSERT INTO 'personnelAdministratif' VALUES(9);
INSERT INTO 'personnelAdministratif' VALUES(10);
INSERT INTO 'personnelAdministratif' VALUES(11);
INSERT INTO 'personnelAdministratif' VALUES(12);
INSERT INTO 'personnelAdministratif' VALUES(13);
INSERT INTO 'personnelAdministratif' VALUES(14);
INSERT INTO 'personnelAdministratif' VALUES(15);
INSERT INTO 'personnelAdministratif' VALUES(16);
INSERT INTO 'personnelAdministratif' VALUES(17);
INSERT INTO 'personnelAdministratif' VALUES(18);
INSERT INTO 'personnelAdministratif' VALUES(19);
INSERT INTO 'personnelAdministratif' VALUES(20);
INSERT INTO 'personnelAdministratif' VALUES(21);
INSERT INTO 'personnelAdministratif' VALUES(22);
INSERT INTO 'personnelAdministratif' VALUES(23);
INSERT INTO 'personnelAdministratif' VALUES(24);
INSERT INTO 'personnelAdministratif' VALUES(25);
INSERT INTO 'personnelAdministratif' VALUES(26);
INSERT INTO 'personnelAdministratif' VALUES(27);
INSERT INTO 'personnelAdministratif' VALUES(28);
INSERT INTO 'personnelAdministratif' VALUES(29);
INSERT INTO 'personnelAdministratif' VALUES(31);
INSERT INTO 'personnelAdministratif' VALUES(32);
INSERT INTO 'personnelAdministratif' VALUES(33);
INSERT INTO 'personnelAdministratif' VALUES(34);
INSERT INTO 'personnelAdministratif' VALUES(35);
INSERT INTO 'personnelAdministratif' VALUES(36);
INSERT INTO 'personnelAdministratif' VALUES(37);
INSERT INTO 'personnelAdministratif' VALUES(38);
INSERT INTO 'personnelAdministratif' VALUES(39);

INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (76,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (65,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (99,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (91,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (58,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (56,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (91,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (71,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (90,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (94,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (54,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (75,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (88,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (59,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (72,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (84,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (74,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (66,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (67,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (77,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (58,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (57,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (77,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (86,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (96,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (64,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (79,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (57,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (70,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (98,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (95,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (60,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (98,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (55,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (52,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (79,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (59,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (56,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (74,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (95,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (98,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (96,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (56,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (58,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (56,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (89,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (55,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (67,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (63,2);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (79,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (51,4);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (63,1);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (82,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (85,3);
INSERT INTO `decharges` (`idEnseignement`,`idStatut`) VALUES (85,4);


INSERT INTO 'typesEnseignements' ('label') VALUES('CM');
INSERT INTO 'typesEnseignements' ('label') VALUES('TD');
INSERT INTO 'typesEnseignements' ('label') VALUES('TP');


INSERT INTO 'coefficients' VALUES(1,2,1);
INSERT INTO 'coefficients' VALUES(1,3,2);
INSERT INTO 'coefficients' VALUES(2,1,1);
INSERT INTO 'coefficients' VALUES(2,2,1);
INSERT INTO 'coefficients' VALUES(2,3,1);
INSERT INTO 'coefficients' VALUES(3,2,1);
INSERT INTO 'coefficients' VALUES(3,3,2);


INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("a",65,20,27,1,1999,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("Pellentesque tincidunt tempus",32,9,22,5,1992,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("vulputate, risus a ultricies adipiscing,",89,18,18,30,2011,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("lacus. Cras interdum.",21,36,4,19,1996,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("neque.",4,7,16,17,1997,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("ultricies adipiscing, enim",55,2,3,32,2002,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("et netus",2,10,29,11,1994,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("quam, elementum at,",73,2,17,33,1993,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("Pellentesque tincidunt tempus",62,18,16,8,2014,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("sed pede",11,6,17,15,2009,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("adipiscing elit. Etiam laoreet,",24,9,2,9,1993,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("nec, eleifend",84,14,24,14,2008,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("justo",8,33,26,26,2004,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("Fusce aliquet magna a neque.",70,17,36,34,1996,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("risus. Donec egestas. Duis",81,23,9,22,2011,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("velit",11,7,2,12,1997,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("congue turpis.",10,35,35,4,1999,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("eu,",87,32,34,11,2016,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("facilisis vitae,",49,19,27,23,2005,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("nonummy ut,",96,20,8,7,2011,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("est ac mattis semper, dui",24,1,1,36,2013,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("euismod urna.",97,35,10,5,2005,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("ac mattis ornare, lectus ante",13,36,16,23,1999,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("orci quis lectus. Nullam suscipit,",15,14,31,30,1991,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("turpis non enim.",91,9,33,8,1994,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("montes, nascetur ridiculus",71,31,2,7,1996,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("viverra. Donec tempus,",96,7,21,14,2012,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("risus varius",45,36,19,29,2000,1);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("tincidunt orci",86,26,14,34,2016,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("nunc id",82,6,30,10,1994,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("luctus felis",28,18,11,1,1999,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("pede, nonummy ut,",14,8,24,23,2012,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("Phasellus ornare. Fusce",53,18,24,10,2013,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("Sed diam",86,25,22,28,1994,5);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("Phasellus nulla. Integer",96,3,7,21,2012,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("eu tellus.",54,18,16,1,1991,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("auctor. Mauris vel turpis.",83,3,10,12,2014,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("et, euismod et, commodo at,",1,29,25,13,1995,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("aliquam, enim",16,20,30,36,1990,3);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("ultrices. Duis volutpat nunc",44,15,36,25,2010,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("arcu.",77,11,26,4,2007,4);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("tempor",25,24,1,16,1997,2);
INSERT INTO 'Ues' ('label','idResponsable','nbHeuresCm','nbHeuresTd','nbHeuresTp','annee','nbMaxApprentis') VALUES ("ipsum. Curabitur",88,15,17,2,2005,4);

INSERT INTO `modesEnseignement` (`label`) VALUES ("pellentesque massa");
INSERT INTO `modesEnseignement` (`label`) VALUES ("nec,");
INSERT INTO `modesEnseignement` (`label`) VALUES ("erat vitae risus.");
INSERT INTO `modesEnseignement` (`label`) VALUES ("Mauris molestie pharetra");
INSERT INTO `modesEnseignement` (`label`) VALUES ("nunc, ullamcorper eu,");

INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (12,52,3,3);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (8,94,1,3);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (17,85,3,1);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (26,91,3,30);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (12,83,2,16);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (2,77,3,33);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (3,87,2,10);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (1,78,2,10);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (24,55,1,20);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (15,67,3,11);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (5,59,2,29);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (30,54,3,16);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (20,71,3,33);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (6,83,2,20);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (13,73,1,20);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (30,82,1,6);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (18,79,1,8);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (12,85,3,31);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (23,99,1,18);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (6,80,2,25);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (11,95,3,28);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (25,51,2,32);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (28,73,3,10);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (16,62,1,36);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (12,71,2,27);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (14,52,3,9);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypesEnseignement`,`nbHeures`) VALUES (17,60,3,11);


INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,4,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,2,3);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,5,3);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,4,4);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,1,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,3,2);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,5,3);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,1,2);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,5,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,2,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,4,4);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,3,4);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,4,3);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,3,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,2,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,5,5);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,5,5);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,3,2);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (1,5,4);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,2,3);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,4,3);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,2,1);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,5,2);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (3,4,4);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`) VALUES (2,1,5);


INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("ut nisi",68,1,8,21,2009,4,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("felis purus ac tellus. Suspendisse",91,1,6,5,2007,4,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("pede, ultrices a, auctor",75,1,7,3,1991,3,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("Vivamus nisi. Mauris",90,1,12,29,1992,1,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("Duis volutpat nunc",96,12,12,2,2012,4,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("vitae",93,10,11,10,2005,5,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("eget metus. In",83,12,5,2,1993,5,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("nec tempus scelerisque,",86,9,5,3,1991,5,8);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("ligula eu enim.",92,8,4,19,2011,2,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("non, dapibus rutrum, justo.",54,11,2,23,2013,5,3);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("lacinia orci, consectetuer euismod est",98,12,8,16,1994,2,2);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("mollis. Duis",72,12,12,19,2003,4,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("semper erat,",88,5,5,13,2015,5,9);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("placerat eget,",57,4,5,5,2016,3,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("vel",61,2,2,20,2013,4,6);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("Cras eu tellus",63,1,2,15,2015,2,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("ut",75,7,5,23,2010,1,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("non, hendrerit id, ante. Nunc",91,4,5,7,1993,5,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("dui,",60,3,7,29,2008,1,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("Mauris eu",86,7,6,33,2000,3,4);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("porttitor vulputate,",86,4,4,34,2003,4,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("natoque",57,11,7,11,2013,4,4);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("aptent taciti sociosqu ad litora",55,4,12,12,1993,1,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("tellus. Aenean egestas hendrerit neque.",92,4,11,22,2001,3,9);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("sem",93,11,8,32,2014,1,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("ac urna. Ut tincidunt vehicula",63,3,2,14,2001,1,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("velit egestas lacinia. Sed congue,",77,12,1,26,2003,1,2);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("dignissim magna",77,1,2,16,2015,2,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("eget metus",93,2,9,7,1992,5,6);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("consectetuer",62,5,11,15,2003,2,4);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("nisi a odio semper",60,10,8,1,2000,1,9);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("eget",71,11,9,4,2012,5,2);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("mauris ut mi. Duis risus",56,9,5,2,2005,3,8);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("egestas nunc",74,6,1,8,2015,3,5);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("pede nec ante blandit viverra.",53,2,2,8,1999,2,8);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("est. Nunc laoreet",96,2,12,1,2009,4,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("luctus lobortis.",65,7,3,36,2013,5,2);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("ut cursus luctus, ipsum leo",66,4,10,18,2005,5,7);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("Nullam suscipit, est ac",86,7,6,29,1995,1,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("mollis.",68,5,5,8,2008,2,1);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("Nullam vitae diam. Proin",91,10,5,33,2002,2,8);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("nibh. Phasellus nulla. Integer",65,6,7,8,1996,1,9);
INSERT INTO `Ues` (`label`,`idResponsable`,`nbHeuresCm`,`nbHeuresTd`,`nbHeuresTp`,`annee`,`nbMaxApprentis`,`idDepartement`) VALUES ("tempor, est ac mattis semper,",91,3,9,3,1995,3,7);


INSERT INTO `departements` (`idDirecteur`) VALUES (67);
INSERT INTO `departements` (`idDirecteur`) VALUES (65);
INSERT INTO `departements` (`idDirecteur`) VALUES (52);
INSERT INTO `departements` (`idDirecteur`) VALUES (93);
INSERT INTO `departements` (`idDirecteur`) VALUES (95);
INSERT INTO `departements` (`idDirecteur`) VALUES (87);
INSERT INTO `departements` (`idDirecteur`) VALUES (72);
INSERT INTO `departements` (`idDirecteur`) VALUES (50);
INSERT INTO `departements` (`idDirecteur`) VALUES (73);


INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (94,15,"2016-05-27 ","aliquet, metus urna");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (56,5,"2017-07-03 ","blandit mattis. Cras");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (75,9,"2017-07-04 ","neque. Morbi quis urna. Nunc");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (87,20,"2017-03-08 ","orci tincidunt adipiscing.");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (27,13,"2016-08-09 ","dolor, nonummy ac, feugiat non,");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (31,12,"2017-11-16 ","arcu. Sed eu nibh vulputate");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (44,20,"2017-04-19 ","Proin");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (59,19,"2017-02-26 ","a tortor.");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (94,17,"2016-12-08 ","adipiscing. Mauris molestie pharetra nibh.");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (42,2,"2017-03-27 ","sit amet");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (44,17,"2017-10-10 ","Quisque");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (98,1,"2016-05-09 ","id, libero. Donec consectetuer mauris");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (46,7,"2017-06-14 ","Suspendisse dui. Fusce");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (31,8,"2017-06-14 ","augue scelerisque mollis.");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (64,18,"2016-08-11 ","mauris sit amet lorem semper");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (92,11,"2017-10-13 ","Donec dignissim magna");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (97,4,"2016-10-31 ","vitae, sodales at, velit.");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (98,15,"2017-10-21 ","arcu");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (96,6,"2016-01-30 ","turpis egestas. Aliquam fringilla cursus");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (9,11,"2016-07-30 ","est ac");
INSERT INTO `attributions` (`idPersonnel`,`idIntervention`,`dateEtHeure`,`commentaire`) VALUES (50,10,"2017-09-05 ","ac,");


INSERT INTO `administrateur` (`id`) VALUES (1);

