

INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("porttitor",0,1,0,0,0);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("Integer",1,1,0,0,0);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("Nunc mauris sapien,",0,1,0,1,1);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("neque. Sed eget",0,0,0,0,1);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("nec,",1,0,1,0,0);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("porttitor scelerisque",0,1,0,1,0);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("Aliquam erat volutpat.",0,1,1,0,1);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("ante.",1,1,0,0,0);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("fringilla",0,0,1,1,1);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("libero",1,0,0,1,1);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("liberoa",1,0,0,1,1);
INSERT INTO 'autorisations' ('label','peutAccorderDroits','peutLireTout','peutAccorderDecharges','peutGererComptes','peutGererUe') VALUES ("Nunc commodo auctor",0,1,0,0,0);


INSERT INTO 'statuts'('label', 'nbHeures', 'annee') VALUES('consultant',12, 2016);
INSERT INTO 'statuts'('label', 'nbHeures', 'annee') VALUES('Enseignant',192, 2016);
INSERT INTO 'statuts'('label', 'nbHeures', 'annee') VALUES('enseignant-chercheur',192, 2016);
INSERT INTO 'statuts'('label', 'nbHeures', 'annee') VALUES('doctorant',96, 2016);
INSERT INTO 'statuts'('label', 'nbHeures', 'annee') VALUES('thésard',20, 2016);


INSERT INTO 'typesEnseignement' ('label') VALUES('CM');
INSERT INTO 'typesEnseignement' ('label') VALUES('TD');
INSERT INTO 'typesEnseignement' ('label') VALUES('TP');


INSERT INTO 'modesEnseignement' ('label') VALUES ("Presentiel");
INSERT INTO 'modesEnseignement' ('label') VALUES ("non Presentiel");
INSERT INTO 'modesEnseignement' ('label') VALUES ("MOOC");
INSERT INTO 'modesEnseignement' ('label') VALUES ("Mauris molestie pharetra");
INSERT INTO 'modesEnseignement' ('label') VALUES ("nunc, ullamcorper eu,");


INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (98,2,5,80,57,1,2013);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (85,4,2,14,64,10,2008);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (78,4,2,41,55,1,1999);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (67,3,1,5,6,7,2009);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (67,1,5,54,72,2,2006);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (66,5,4,24,56,4,2015);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (70,4,3,80,72,7,1992);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (69,4,1,76,19,7,2011);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (64,5,4,66,60,5,2010);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (92,3,2,45,60,8,1998);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (77,2,2,7,64,3,2010);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (88,1,5,7,58,10,2014);
INSERT INTO `coefficients` (`idTypeEnseignement`,`idStatut`,`idModeEnseignement`,`valeurNormale`,`valeurHeureSup`,`priorite`,`annee`) VALUES (59,1,5,67,72,10,2009);


INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nec,","EEW46JOH3ZJ","Colon","Caleb","neque@Nullam.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("egestas","TFC93CVL3XR","Kerr","Ebony","ante.bibendum.ullamcorper@iaculis.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("dis","QGY00CST2FD","Greene","Carter","Nunc.laoreet.lectus@veliteusem.com",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fringilla","IXU53RIX6IQ","Macias","Chase","nec.orci@eu.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("viverra.","VJP36TGB0XY","Sheppard","Lunea","vulputate.eu@sed.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Curabitur","UHB01URD1WU","Cherry","Hyatt","metus.urna@est.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vel,","QCR48DLB3UE","Poole","Fleur","rhoncus@diamDuismi.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fermentum","SAZ27YVT9JU","Joyce","Eden","quis.arcu.vel@Loremipsumdolor.edu",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Sed","PHF33NWR8SX","Warren","Harlan","Nunc.mauris.elit@leo.org",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("quis","JNL90ZNQ7UL","Finley","Ariel","Proin@ligulaAliquam.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Quisque","BOJ24NBO6TD","Emerson","Akeem","ante@porta.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("a,","HIG10WGM1WB","Mcclain","Illana","magna.Ut.tincidunt@enimEtiamgravida.ca",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("odio.","XWO43XXL8KB","Ferguson","Ifeoma","eu.eleifend@auguemalesuada.net",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("molestie","YUU17SBJ7VD","Olson","Quamar","neque@rutrumeuultrices.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ipsum","IVG31KHC6QB","Schroeder","Irene","dolor.sit.amet@sagittislobortismauris.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("arcu.","UDE11KSZ4BG","Jenkins","Troy","felis@acliberonec.net",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("tellus.","DII05GTO2SX","Alvarez","Rinah","lacinia.at.iaculis@Utnecurna.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("neque","RZY50XDE1YD","Koch","Gemma","dictum.eu@tincidunttempusrisus.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("accumsan","LLX79EVE8SG","Whitfield","Amaya","arcu.iaculis.enim@VivamusrhoncusDonec.com",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Ut","VEP67BVY8JK","Hahn","Suki","dolor.Quisque.tincidunt@euduiCum.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("venenatis","JZA85OLQ5DY","Durham","Inga","nec.ante@iaculisodio.net",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("risus.","HSN26QVA5PZ","Weiss","Doris","Proin@diamPellentesque.org",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("fames","CGH96LTF0WJ","Mckinney","Kelly","Ut.semper@elementum.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Mauris","XWH81HDR5KW","Mays","Alyssa","sed.sapien.Nunc@egestasSedpharetra.com",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("imperdiet","KJE80RII0NL","Austin","Acton","Curabitur.dictum@Maecenaslibero.edu",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("commodo","OAC13ERB1EK","Lloyd","Lawrence","scelerisque@cursuset.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("est","CQP10TWV7KP","Stevenson","Nelle","Cras@euplacerat.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ligula","LGD63LVB0CD","Webster","Evelyn","consectetuer.adipiscing@ante.co.uk",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nibh.","VMH81UDW8IZ","Fox","Giselle","Cras.lorem@dolorsitamet.net",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("hvcgfbt","OKV96IEQ6ZN","Santiago","Patrick","magna.Praesent.interdum@lacus.com",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ornare.","IPJ06LIP8LP","Williamson","Anastasia","lacinia@neque.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("hlgbj","HGH97TRO1GP","Horton","Ria","mauris.sit.amet@velquam.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Donec","DRM71OZA5EE","Stuart","Sasha","quis.arcu@SedmolestieSed.co.uk",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("feugiat.","OKW07BZE3JQ","Norris","Mercedes","non.lobortis.quis@VivamusnisiMauris.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("metus.","TPK53QNW1VW","Camacho","Vivian","aliquet.Phasellus.fermentum@ipsum.com",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("convallis","BNC74RZJ7QE","Riggs","Mason","Mauris.vel.turpis@urnaUttincidunt.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("feugiat","NOG45OSH3PS","Shepard","Jenette","Pellentesque.habitant@nisisemsemper.ca",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vulputate","IQY89PXN1VM","Bolton","Maxwell","vel.est.tempor@vitaeodio.com",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("elementum","UGD35TMJ0XF","Rojas","Anjolie","arcu@velvulputate.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("mauris","RLJ41WQG3FX","Powers","Nathan","posuere@pellentesque.com",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("sodales","PZC57GDK1FM","Hart","Tasha","eget.nisi@Vivamus.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("aliquet.","ORP39NJV9TU","Glover","Dominic","Duis.ac@justofaucibus.co.uk",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ut","BWC81USD7VT","Potts","Nero","lacus@Aliquam.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Nulla","ZBT25RPL5XK","Banks","Mira","arcu.Morbi@tellusid.net",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("lectus","WGB34XIS4ZG","Wells","Samantha","faucibus.Morbi.vehicula@aliquet.net",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("diam.","YRV19NWA8CJ","Mcfarland","Denise","aliquet@necimperdiet.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("aliquet","MNZ23JMZ6WE","Graves","Branden","Nulla.aliquet@Donecelementum.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("dolor","MKU25IZT7UA","Burks","Tanya","lacus.Nulla.tincidunt@tortorIntegeraliquam.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Vestibulum","JWR88ZOC1KM","Burns","Blaze","sem.mollis.dui@fringilla.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("edzqs","QPK28HNP0ZR","Suarez","Ima","In.nec.orci@luctusCurabitur.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("velit.","GMP15ETY1RW","Nicholson","Russell","velit.egestas@Fuscediam.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("quis,","ATR11NDU0CS","Briggs","Chandler","sed@sollicitudina.ca",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("auctor","BKG82JWC2HX","Cox","Demetrius","sagittis.semper@velitPellentesqueultricies.com",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("parturient","HLJ98IMQ8CZ","Glenn","Craig","nunc.ac.mattis@tortorInteger.ca",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("rhoncus.","KSD92JEG3ND","Allison","Ariel","ante.ipsum.primis@risus.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("frtvgy","UKT41JDS4SF","Good","Jocelyn","Aenean@nec.ca",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nulla.","UYE81ITX9NH","Rivers","Amy","sollicitudin.adipiscing@iaculisenimsit.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("luctus","CVH26TXV7JZ","Dennis","Curran","elit.Etiam.laoreet@blanditcongueIn.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("lectus.","KQO73CAS2AU","Gould","Chester","ornare@actellusSuspendisse.com",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nisi.","ROZ09XCX4MK","Barr","Ivor","massa.rutrum@feugiatmetus.org",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("vitae","KVK41QJH6VP","Wilder","Kristen","tempor@Maurisnon.net",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("sit","BXQ82KLG0VC","Morin","Tad","Praesent@ornare.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("id","FHZ67UWY3ZC","Mccarty","Deanna","egestas.Sed.pharetra@convalliserateget.net",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("eros","JWR13ZKO9UF","Moss","Aubrey","sodales@liberoMorbi.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Integer","DNK00SOQ7IQ","Mercer","Kimberly","luctus.felis@sit.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("nunc","NAT32GOC1TL","Sweeney","Julie","venenatis.a@sollicitudin.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Suspendisse","IXN49RXR4JA","Sykes","Maxwell","non@tinciduntorci.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ultricies","PNY25KJO9CA","Santos","Philip","fames@egetmetuseu.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("htybnuj","MKK29HSU3RH","Adkins","Bradley","urna.nec@amet.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("jynhtrg.","LJT13EEO3KD","Dixon","Hamish","elit.pede@mollis.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("rgbv","SCJ80CKP4CL","Morgan","Abigail","nascetur.ridiculus@Maecenaslibero.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("et","VLV76VVC3EL","Best","Ethan","sit.amet@commodoipsumSuspendisse.co.uk",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ilom","RUL81TQF2RC","Mcguire","Dylan","augue.malesuada@enim.com",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("arcu","JXJ70HXK4MS","Osborne","Daquan","magnis.dis@egetlaoreetposuere.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ante","FOM51XIR8NO","Glover","John","facilisi@Curabiturvel.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("oiluk","DIR34ZBZ0KX","Guzman","Blaine","pharetra@sed.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("risus","OGO64XNW5RF","Delaney","Nathaniel","Duis.mi@faucibus.edu",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("loikujyhtgtf,","SJT00UGL6SO","Mcneil","Melyssa","faucibus.orci@ac.com",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("diam","NEQ99HUZ4TI","Buckley","Shelly","at.fringilla.purus@Maurismolestie.ca",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("orci.","EEC88NQB6KJ","Tyson","Sierra","neque@Maecenas.edu",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("euismod","NDU26IWG7YB","Moreno","Guy","eget.nisi@nibh.net",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("liokuyjuthrgefrd","HDQ71YKR5FW","Flores","Anjolie","facilisi.Sed@imperdieteratnonummy.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("Nuflla","ONY49WJL3PS","Moss","Rana","ut@Phasellusdapibusquam.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("convallis,","QZJ23ESV8QV","Porter","Calista","ultrices.iaculis.odio@estvitaesodales.net",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("egestas.","RXK73ZYQ2XZ","Estrada","Amir","lobortis.ultrices.Vivamus@lobortisquam.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("adipiscing","AFB11AVF0RL","Solis","Trevor","eu.euismod@quamelementum.org",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ornare","KLT72RPT2SW","Kim","Melinda","erat@fringillaporttitorvulputate.edu",2);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("et,","VFL63NNS4YK","Flynn","Alexis","enim@porttitor.net",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("tellus","QEB62NKW0CB","Graham","Harper","augue.id@augueeu.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("rtgb.","HSO98HSY2TW","Salazar","Regan","justo@luctusetultrices.org",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("auctor,","BHR20IEL4EI","Stafford","Eagan","gravida.molestie.arcu@maurisMorbinon.co.uk",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("a","FCX19TEJ2NA","Forbes","Tatiana","eu.accumsan.sed@Curabitur.co.uk",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ikjuhygtefrdzerghty,","EDB09IXS8ED","Olson","Chandler","luctus.et.ultrices@porttitortellus.ca",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("justo.","BCI65ZGZ5KT","Pena","Colton","Nam.porttitor.scelerisque@eu.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("at,","YZT58ZVE1VK","Meyers","Chloe","non@sodalesat.org",4);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("ebgmoihergehrfhiuzugerhfherufurheghergjerju","EPD41SOD4LL","Riggs","Bethany","Cras@ultricesiaculis.edu",5);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("hzifkjedvoerhvezbu","NCL46QPG3PK","Brock","Abbot","dui.in@mollisneccursus.net",3);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("quam","HQO11SQI0RI","Skinner","Laura","quam.Pellentesque@nonummyultriciesornare.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("tempus","QTA94QYJ7DS","Camacho","Kelsey","convallis.dolor.Quisque@Vestibulumanteipsum.co.uk",1);
INSERT INTO 'personnel' ('login','motDePasse','nom','prenom','mail','idAutorisation') VALUES ("turpis.","ODB38JFK1AW","Dotson","Cassady","mauris@cursusinhendrerit.net",3);


INSERT INTO 'personnelEnseignant' VALUES(50,4);
INSERT INTO 'personnelEnseignant' VALUES(51,1);
INSERT INTO 'personnelEnseignant' VALUES(52,3);
INSERT INTO 'personnelEnseignant' VALUES(53,1);
INSERT INTO 'personnelEnseignant' VALUES(54,2);
INSERT INTO 'personnelEnseignant' VALUES(55,2);
INSERT INTO 'personnelEnseignant' VALUES(56,2);
INSERT INTO 'personnelEnseignant' VALUES(57,2);
INSERT INTO 'personnelEnseignant' VALUES(58,1);
INSERT INTO 'personnelEnseignant' VALUES(59,2);
INSERT INTO 'personnelEnseignant' VALUES(60,1);
INSERT INTO 'personnelEnseignant' VALUES(61,1);
INSERT INTO 'personnelEnseignant' VALUES(62,2);
INSERT INTO 'personnelEnseignant' VALUES(63,1);
INSERT INTO 'personnelEnseignant' VALUES(64,1);
INSERT INTO 'personnelEnseignant' VALUES(65,2);
INSERT INTO 'personnelEnseignant' VALUES(66,1);
INSERT INTO 'personnelEnseignant' VALUES(67,1);
INSERT INTO 'personnelEnseignant' VALUES(68,1);
INSERT INTO 'personnelEnseignant' VALUES(69,1);
INSERT INTO 'personnelEnseignant' VALUES(70,3);
INSERT INTO 'personnelEnseignant' VALUES(71,3);
INSERT INTO 'personnelEnseignant' VALUES(72,2);
INSERT INTO 'personnelEnseignant' VALUES(73,1);
INSERT INTO 'personnelEnseignant' VALUES(74,4);
INSERT INTO 'personnelEnseignant' VALUES(75,2);
INSERT INTO 'personnelEnseignant' VALUES(76,3);
INSERT INTO 'personnelEnseignant' VALUES(77,4);
INSERT INTO 'personnelEnseignant' VALUES(78,1);
INSERT INTO 'personnelEnseignant' VALUES(79,4);
INSERT INTO 'personnelEnseignant' VALUES(80,1);
INSERT INTO 'personnelEnseignant' VALUES(81,1);
INSERT INTO 'personnelEnseignant' VALUES(82,3);
INSERT INTO 'personnelEnseignant' VALUES(83,1);
INSERT INTO 'personnelEnseignant' VALUES(84,4);
INSERT INTO 'personnelEnseignant' VALUES(85,2);
INSERT INTO 'personnelEnseignant' VALUES(86,1);
INSERT INTO 'personnelEnseignant' VALUES(87,1);
INSERT INTO 'personnelEnseignant' VALUES(88,1);
INSERT INTO 'personnelEnseignant' VALUES(89,1);
INSERT INTO 'personnelEnseignant' VALUES(90,4);
INSERT INTO 'personnelEnseignant' VALUES(91,1);
INSERT INTO 'personnelEnseignant' VALUES(92,1);
INSERT INTO 'personnelEnseignant' VALUES(93,4);
INSERT INTO 'personnelEnseignant' VALUES(94,4);
INSERT INTO 'personnelEnseignant' VALUES(95,1);
INSERT INTO 'personnelEnseignant' VALUES(96,1);
INSERT INTO 'personnelEnseignant' VALUES(97,2);
INSERT INTO 'personnelEnseignant' VALUES(98,1);
INSERT INTO 'personnelEnseignant' VALUES(99,1);


INSERT INTO 'personnelAdministratif' VALUES(2);
INSERT INTO 'personnelAdministratif' VALUES(3);
INSERT INTO 'personnelAdministratif' VALUES(4);
INSERT INTO 'personnelAdministratif' VALUES(5);
INSERT INTO 'personnelAdministratif' VALUES(6);
INSERT INTO 'personnelAdministratif' VALUES(7);
INSERT INTO 'personnelAdministratif' VALUES(8);
INSERT INTO 'personnelAdministratif' VALUES(9);
INSERT INTO 'personnelAdministratif' VALUES(10);
INSERT INTO 'personnelAdministratif' VALUES(11);
INSERT INTO 'personnelAdministratif' VALUES(12);
INSERT INTO 'personnelAdministratif' VALUES(13);
INSERT INTO 'personnelAdministratif' VALUES(14);
INSERT INTO 'personnelAdministratif' VALUES(15);
INSERT INTO 'personnelAdministratif' VALUES(16);
INSERT INTO 'personnelAdministratif' VALUES(17);
INSERT INTO 'personnelAdministratif' VALUES(18);
INSERT INTO 'personnelAdministratif' VALUES(19);
INSERT INTO 'personnelAdministratif' VALUES(20);
INSERT INTO 'personnelAdministratif' VALUES(21);
INSERT INTO 'personnelAdministratif' VALUES(22);
INSERT INTO 'personnelAdministratif' VALUES(23);
INSERT INTO 'personnelAdministratif' VALUES(24);
INSERT INTO 'personnelAdministratif' VALUES(25);
INSERT INTO 'personnelAdministratif' VALUES(26);
INSERT INTO 'personnelAdministratif' VALUES(27);
INSERT INTO 'personnelAdministratif' VALUES(28);
INSERT INTO 'personnelAdministratif' VALUES(29);
INSERT INTO 'personnelAdministratif' VALUES(31);
INSERT INTO 'personnelAdministratif' VALUES(32);
INSERT INTO 'personnelAdministratif' VALUES(33);
INSERT INTO 'personnelAdministratif' VALUES(34);
INSERT INTO 'personnelAdministratif' VALUES(35);
INSERT INTO 'personnelAdministratif' VALUES(36);
INSERT INTO 'personnelAdministratif' VALUES(37);
INSERT INTO 'personnelAdministratif' VALUES(38);
INSERT INTO 'personnelAdministratif' VALUES(39);


INSERT INTO 'administrateurs' ('id') VALUES (1);


INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (92,"vitae sodales nisi magna sed dui. Fusce aliquam, enim",23,1994);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (61,"vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque",13,1990);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (76,"Nam ac nulla. In tincidunt congue turpis. In condimentum.",26,2012);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (55,"tortor. Integer aliquam adipiscing lacus. Ut nec urna",21,1997);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (50,"dolor",30,2002);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (70,"eu, placerat eget, venenatis a,",26,2000);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (50,"est, vitae sodales nisi",30,2008);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (78,"eros turpis non enim. Mauris quis",22,1994);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (84,"ut odio vel",21,1997);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (76,"Proin nisl",20,1991);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (96,"scelerisque neque sed sem",18,1996);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (61,"Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum",6,1991);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (59,"faucibus",2,2003);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (87,"orci luctus et ultrices posuere",20,2015);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (60,"Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet,",9,2005);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (59,"leo, in",12,2007);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (66,"pretium aliquet, metus urna convallis erat, eget",27,2010);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (67,"In tincidunt congue turpis.",13,2002);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (60,"Mauris quis turpis vitae",7,2010);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (55,"amet, consectetuer",2,1991);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (86,"aliquet odio. Etiam ligula tortor,",9,1997);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (88,"arcu. Morbi sit amet massa. Quisque porttitor",20,1995);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (55,"in lobortis tellus justo sit amet nulla. Donec non justo.",28,2011);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (91,"diam eu",30,1993);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (50,"ante ipsum primis in",29,2015);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (57,"non sapien molestie orci tincidunt adipiscing. Mauris",26,2007);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (69,"dui, in",25,2003);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (96,"nec, imperdiet nec, leo.",12,2008);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (93,"gravida sagittis. Duis gravida. Praesent eu nulla at",17,1992);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (72,"quis turpis vitae purus gravida sagittis. Duis gravida.",3,1991);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (96,"scelerisque",4,2004);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (78,"fringilla euismod enim. Etiam",19,2003);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (66,"quis",18,1991);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (97,"vulputate mauris sagittis placerat. Cras dictum ultricies ligula.",9,1998);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (88,"hendrerit id, ante. Nunc",20,2012);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (88,"torquent per conubia nostra, per inceptos",17,1997);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (71,"arcu. Vivamus sit amet risus. Donec egestas.",26,2000);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (68,"quis,",15,1992);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (89,"Nulla dignissim. Maecenas ornare egestas",12,2007);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (72,"natoque penatibus et magnis dis",9,1993);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (97,"ullamcorper,",11,2003);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (87,"consectetuer adipiscing elit. Etiam laoreet, libero",11,2004);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (63,"est.",26,1996);
INSERT INTO 'decharges' ('idEnseignant','raison','duree','annee') VALUES (62,"nec,",3,1993);


INSERT INTO 'departements' ('idDirecteur') VALUES (67);
INSERT INTO 'departements' ('idDirecteur') VALUES (65);
INSERT INTO 'departements' ('idDirecteur') VALUES (52);
INSERT INTO 'departements' ('idDirecteur') VALUES (93);
INSERT INTO 'departements' ('idDirecteur') VALUES (95);
INSERT INTO 'departements' ('idDirecteur') VALUES (87);
INSERT INTO 'departements' ('idDirecteur') VALUES (72);
INSERT INTO 'departements' ('idDirecteur') VALUES (50);
INSERT INTO 'departements' ('idDirecteur') VALUES (73);


INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("EHII-39144D","eu augue",82,7,2015,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("UQBU-69684O","turpis nec",52,7,2002,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("TFXO-86855F","pulvinar arcu",69,1,2010,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("QBVN-56833F","ligula. Nullam",94,5,2001,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("AJWU-52385E","ante ipsum primis",62,4,2009,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("MYDA-15517N","libero mauris,",63,6,2013,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("SXDR-75958W","sagittis placerat.",68,2,1994,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("FXVC-18254B","non enim.",92,6,2002,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("FPZZ-14825L","Nullam suscipit, est",62,7,2013,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("ISFF-38823S","sed,",69,7,2011,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("JNZI-81871S","Nunc pulvinar",57,7,2005,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("HUZA-26475T","rhoncus. Donec",53,1,2011,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("HPHW-51851P","Proin",89,9,1997,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("QHYD-54956L","rutrum",69,5,1994,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("JFOS-11573P","Donec",63,7,1992,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("HQAL-53951F","ac",51,6,2012,5);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("SXBS-42492F","tempor erat",61,6,2003,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("GMKP-95145Q","Proin",81,7,2008,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("OPKY-66586D","a, facilisis",95,3,1990,4);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("OXXN-27726B","Duis a mi",83,3,1990,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("XBZU-74571L","eu sem.",57,8,2002,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("HSTC-59354X","libero. Proin",73,2,1998,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("DDJC-18111S","quis lectus. Nullam",51,4,1996,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("AIIC-98856R","sed libero.",54,8,1990,4);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("VZQC-36164M","Cras lorem lorem,",50,5,1991,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("QQSJ-64673D","rutrum",53,2,2015,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("AOTN-49127X","arcu iaculis",68,5,2009,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("ORUG-87378T","Sed",57,9,1992,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("GVTA-58258Z","ultrices. Vivamus rhoncus.",67,2,2015,6);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("VTJF-76222M","neque. Nullam ut",53,8,1993,4);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("EGVV-45433H","massa lobortis",97,1,1992,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("OSOE-62874W","ac mi eleifend",98,8,2011,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("HMDK-79624Q","at,",54,7,1994,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("SQNV-43545M","parturient montes,",60,5,2005,4);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("SMFD-88492Y","erat",57,1,1992,3);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("EYZF-59446K","ornare,",63,6,1993,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("RDIV-17929C","feugiat. Sed",67,1,1994,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("CSAS-45579E","ante",64,1,2004,5);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("GJCQ-94132L","eget nisi dictum",91,9,1994,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("PLWG-77615U","id, erat.",51,7,2016,1);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("UGKB-69414D","et ultrices",97,4,1995,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("MGZL-69514V","Aenean",88,7,1998,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("VQLF-71737L","odio tristique pharetra.",91,6,1996,2);
INSERT INTO 'Ues' ('code','label','idResponsable','idDepartement','annee','nbMaxApprentis') VALUES ("HEFI-99777D","magna. Cras convallis",53,3,2006,6);


INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (38,70,1,2,46,2016);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (20,88,2,3,35,1991);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (27,62,2,2,59,1999);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (11,63,2,1,39,2000);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (1,71,3,1,32,1996);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (10,91,2,1,74,1998);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (25,93,1,4,3,1999);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (16,75,2,4,20,1996);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (2,74,2,5,66,1996);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (26,98,3,2,81,2001);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (29,97,3,5,7,1997);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (37,51,3,5,70,1993);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (21,66,1,4,89,2012);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (20,84,3,2,18,2003);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (4,74,2,5,56,2011);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (14,84,2,5,85,2002);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (36,65,2,1,12,2011);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (14,88,2,4,1,1996);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (9,56,3,5,57,2011);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (6,56,2,1,78,1994);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (35,90,2,5,16,1996);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (30,54,3,4,22,2004);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (24,93,1,4,78,2002);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (40,80,2,2,77,1994);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (27,91,3,5,23,1995);
INSERT INTO `interventions` (`idUE`,`idEnseignant`,`idTypeEnseignement`,`idModeEnseignement`,`nbHeures`,`annee`) VALUES (6,97,3,2,67,1999);


INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (17,2,17);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (34,3,10);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (17,1,7);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (12,1,35);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (11,2,25);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (25,2,27);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (7,2,34);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (16,3,6);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (4,2,1);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (8,3,17);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (5,2,18);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (20,3,12);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (28,3,28);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (9,1,11);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (5,1,22);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (15,3,21);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (10,2,14);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (9,2,36);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (3,1,14);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (4,1,9);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (13,2,32);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (13,3,32);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (40,2,1);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (19,1,13);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (5,3,35);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (18,2,1);
INSERT INTO 'nombreHeures' ('idUE','idTypeEnseignement','quantite') VALUES (25,3,6);


INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (3,30,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (47,10,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (83,20,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (45,34,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (29,1,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (85,38,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (40,19,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (60,29,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (95,4,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (56,19,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (62,28,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (64,36,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (8,9,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (19,16,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (36,11,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (31,33,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (48,40,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (95,25,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (72,3,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (34,18,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (96,20,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (79,2,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (97,40,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (67,28,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (2,20,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (22,39,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (68,33,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (20,4,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (42,15,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (63,12,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (28,16,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (44,18,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (74,26,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (6,2,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (83,34,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (66,11,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (87,30,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (58,32,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (80,11,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (32,6,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (93,25,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (47,2,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (15,7,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (25,35,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (16,29,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (14,13,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (68,28,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (53,23,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (66,3,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (25,29,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (12,33,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (37,36,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (7,17,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (95,21,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (67,30,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (77,1,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (18,20,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (38,32,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (97,23,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (60,15,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (100,36,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (21,4,0,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (44,5,1,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (36,8,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (12,35,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (4,35,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (76,14,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (74,30,0,0);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (30,2,1,1);
INSERT INTO 'autorisationsSurUes' ('idPersonnel','idUe','peutModifierAttributions','peutLireUe') VALUES (54,35,0,1);


INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (94,15,"2016-05-27 ","aliquet, metus urna");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (56,5,"2017-07-03 ","blandit mattis. Cras");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (75,9,"2017-07-04 ","neque. Morbi quis urna. Nunc");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (87,20,"2017-03-08 ","orci tincidunt adipiscing.");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (27,13,"2016-08-09 ","dolor, nonummy ac, feugiat non,");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (31,12,"2017-11-16 ","arcu. Sed eu nibh vulputate");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (44,20,"2017-04-19 ","Proin");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (59,19,"2017-02-26 ","a tortor.");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (94,17,"2016-12-08 ","adipiscing. Mauris molestie pharetra nibh.");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (42,2,"2017-03-27 ","sit amet");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (44,17,"2017-10-10 ","Quisque");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (98,1,"2016-05-09 ","id, libero. Donec consectetuer mauris");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (46,7,"2017-06-14 ","Suspendisse dui. Fusce");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (31,8,"2017-06-14 ","augue scelerisque mollis.");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (64,18,"2016-08-11 ","mauris sit amet lorem semper");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (92,11,"2017-10-13 ","Donec dignissim magna");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (97,4,"2016-10-31 ","vitae, sodales at, velit.");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (98,15,"2017-10-21 ","arcu");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (96,6,"2016-01-30 ","turpis egestas. Aliquam fringilla cursus");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (9,11,"2016-07-30 ","est ac");
INSERT INTO 'attributions' ('idPersonnel','idIntervention','dateEtHeure','commentaire') VALUES (50,10,"2017-09-05 ","ac,");

